BOARD_SIZE = 800
PANEL_WIDTH = 300

WIDTH = BOARD_SIZE + PANEL_WIDTH
HEIGHT = BOARD_SIZE

ROWS = 8
COLS = 8

SQSIZE = BOARD_SIZE // COLS  

print("WIDTH =", WIDTH)
print("HEIGHT =", HEIGHT)
print("SQSIZE =", SQSIZE)